backend:
  name: github
  repo: RandomAmbersky/test-netlify-cms # Path to your GitHub repository
media_folder: public/img #images that are uploaded via Netlify Cms interface will be stored in this folder
public_folder: img #I dont know
collections:
  - name: "news_ru" # Used in routes, e.g., /admin/collections/blog
    label: "Новости (RU)" # Used in the UI
    folder: "content/ru/news" # The path to the folder where the markdown files are stored
    create: true # Allow users to create new markdown files.
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for front matter. You will need to modify fields according to your project.
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Краткое описание", name: "description", widget: "string"}
      - {label: "Текст", name: "body", widget: "markdown"}
  - name: "news_sr" # Used in routes, e.g., /admin/collections/blog
    label: "Новости (SR)" # Used in the UI
    folder: "content/sr/news" # The path to the folder where the markdown files are stored
    create: true # Allow users to create new markdown files.
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for front matter. You will need to modify fields according to your project.
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Краткое описание", name: "description", widget: "string"}
      - {label: "Текст", name: "body", widget: "markdown"}
  - name: "cases_ru" # Used in routes, e.g., /admin/collections/blog
    label: "Кейсы (RU)" # Used in the UI
    folder: "content/ru/cases" # The path to the folder where the markdown files are stored
    create: true # Allow users to create new markdown files.
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for front matter. You will need to modify fields according to your project.
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Краткое описание", name: "description", widget: "string"}
      - {label: "Текст", name: "body", widget: "markdown"}
  - name: "cases_sr" # Used in routes, e.g., /admin/collections/blog
    label: "Кейсы (SR)" # Used in the UI
    folder: "content/sr/cases" # The path to the folder where the markdown files are stored
    create: true # Allow users to create new markdown files.
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for front matter. You will need to modify fields according to your project.
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Краткое описание", name: "description", widget: "string"}
      - {label: "Текст", name: "body", widget: "markdown"}
